version: "3.8"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - db-data:/app/backend
      - ./logs:/app/logs
      - ./screenshots:/app/screenshots
    restart: unless-stopped

volumes:
  db-data:
